backend:
  name: git-gateway
  branch: redesign

site_url: "https://brutus-things-11ty.netlify.app"
display_url: "https://brutus-things-11ty.netlify.app"

media_folder: static/img/uploads

collections:
  - label: Things
    name: things
    create: true
    folder: src/pages/things
    fields:
      - widget: string
        label: Thing Title
        name: title
      - widget: list
        label: Images
        name: images
        fields:
          - { widget: image, label: Image, name: image }
          - { widget: text, label: Description, name: description }
      - widget: string
        label: Permalink
        name: permalink
        hint: 'Must follow this pattern: "/thing/name-of-thing/"'
        pattern: ['^\/thing\/[^\s]+\/$', '/thing/name-of-thing/']

  - label: Pages
    name: pages
    files:
      - label: Profile Page
        name: profile
        file: src/pages/profile/content.md
        fields:
          - { widget: hidden, name: permalink, default: false }
          - { widget: string, label: Page Title, name: title }
          - { widget: markdown, label: Body, name: body }
      - label: Workshop Page
        name: workshop
        file: src/pages/workshop/content.md
        fields:
          - { widget: hidden, name: permalink, default: false }
          - { widget: string, label: Page Title, name: title }
          - { widget: markdown, label: Body, name: body }
