backend:
  name: git-gateway
  branch: redesign

site_url: "https://brutus-things-11ty.netlify.app"
display_url: "https://brutus-things-11ty.netlify.app"

media_folder: static/img/uploads

collections:
  - label: Things
    name: things
    create: true
    folder: src/pages/things-collection
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - label: Images
        name: images
        widget: list
        fields:
          - { label: Image, name: image, widget: image }
          - { label: Description, name: description, widget: text }

  - label: Pages
    name: pages
    files:
      - label: About Page
        name: about
        file: src/pages/content/about.md
        fields:
          - { label: Page Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - label: Workshop Page
        name: workshop
        file: src/pages/content/workshop.md
        fields:
          - { label: Page Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
