backend:
  name: git-gateway
  branch: redesign

site_url: "https://brutus-things-11ty.netlify.app"
display_url: "https://brutus-things-11ty.netlify.app"

media_folder: static/img/uploads

collections:
  - label: Things
    name: things
    create: true
    folder: src/pages/things
    fields:
      - widget: string
        label: Thing Title
        name: title
      - widget: list
        label: Images
        name: images
        fields:
          - { widget: image, label: Image, name: image }
          - { widget: text, label: Description, name: description }

  - label: Pages
    name: pages
    files:
      - label: About Page
        name: about
        file: src/pages/content/about.md
        fields:
          - { widget: string, label: Page Title, name: title }
          - { widget: markdown, label: Body, name: body }
      - label: Workshop Page
        name: workshop
        file: src/pages/content/workshop.md
        fields:
          - { widget: string, label: Page Title, name: title }
          - { widget: markdown, label: Body, name: body }
